### ISSUE TITLE
Still go on this project?

### ISSUE THREAD

**Issue by zhengqiwen1997** [wichtounet/thor-os#48]
Hi, I just want to ask if you are still working on this project. If not, why?

**Comment by wichtounet** [comment]
Hi

At this current time, I am not working on this project. 

I stopped most of my development projects for about 5 years and did not have time to pursue them again until recently. I am currently restarting some of my projects. I would like to restart thor-os as well, but I have no idea when I will have the time because this is a complex project and I need to have significant periods of time to concentrate to imagine working on any feature here, which is a luxury I rarely enjoy these days.

**Comment by zhengqiwen1997** [comment]
Hi, thanks for reply. I recently want to develop a toy OS on my own for fun as well, and I find your project really interesting and I should learn a lot from you. Anyway, good luck for your work, hope you can find some spare time on this project in the future. :-)
